"""empty message

Revision ID: a65730b8cdbf
Revises: 
Create Date: 2022-03-10 08:37:05.698219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65730b8cdbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jogadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('jogadas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simbolo', sa.String(length=30), nullable=False),
    sa.Column('jogador_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jogador_id'], ['jogadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogadas')
    op.drop_table('jogadores')
    # ### end Alembic commands ###
